name: barzido
description: Seoul Itaewon and Hongdae pub map app.
homepage: "https://jtsgrit0.github.io/barzido"
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: any
  equatable: any
  get_it: any
  dio: any
  geolocator: any
  google_maps_flutter: any
  google_maps_webservice: any
  flutter_dotenv: any
  cloud_firestore: ^4.15.0
  firebase_core: ^2.24.0
  provider: ^6.1.1
  intl: ^0.19.0
  cached_network_image: ^3.3.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.5

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/icons/