name: barzido
description: Seoul Itaewon and Hongdae pub map app.
homepage: "https://jtsgrit0.github.io/barzido"
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  get_it: ^9.2.1
  dio: ^5.9.2
  geolocator: ^14.0.2
  flutter_naver_map: ^1.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.5

flutter:
  uses-material-design: true